Repository galio-org/galio, pull requests merged in 2019-09, with the labels that each got.

#94 hitSlop added to left icon
  src/NavBar.js
Labels: Accepted for next version, Status: Accepted, Type: Enhancement

#99 add onRef prop to Input component for passing ref to rn text input
  src/Input.js
Labels: Accepted for next version, Status: Accepted, Type: Enhancement

#108 added font awesome 5
  src/helpers/getIconType.js
Labels: Accepted for next version, Status: Accepted, Type: Enhancement

#123 Components/accordion
  src/Accordion.js
  src/index.js
Labels: Accepted for next version, Type: Enhancement

#124 Components/deck swiper
  src/DeckSwiper.js
  src/index.js
Labels: Accepted for next version, Type: Enhancement

#112 Components/toast notification
  src/Toast.js
  src/index.js
Labels: Accepted for next version, Status: Accepted, Type: Enhancement

#116 issue #104 resolved
  src/Block.js
  src/Button.js
  src/Card.js
  src/Checkbox.js
  src/Icon.js
  src/Input.js
  src/NavBar.js
  src/Radio.js
  src/Slider.js
  src/Switch.js
  src/Text.js
  src/index.js
Labels: Accepted for next version, Type: Enhancement

#129 fix NavBar variable bug
  src/NavBar.js
Labels: Status: Accepted, Type: Enhancement
