Repository galio-org/galio, pull requests merged in 2020-01, with the labels that each got.

#163 refactor: changed variables
  src/theme/colors.js
  src/theme/sizes.js
Labels: Status: Review Needed, v1.0

#164 Components/icon
  src/Icon.js
Labels: Accepted for next version, v1.0

#165 Components/Text
  src/Text.js
Labels: Status: Review Needed, v1.0

#145 re-add onRef prop
  src/Input.js
Labels: Accepted for next version, Type: Enhancement

#167 feat: Link component
  src/Link.js
  src/index.js
Labels: Status: Pending

#168 Feature/button
  src/Button.js
  src/theme/sizes.js
Labels: v1.0

#170 Ions atomic design
  src/atomic/atoms/Button.js
  src/atomic/atoms/Input.js
  src/atomic/atoms/Link.js
  src/atomic/ions/Icon.js
  src/atomic/ions/Text.js
  src/index.js
  src/theme/sizes.js
Labels: v1.0
